Traceback (most recent call last):
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 294, in <module>
    main(x1=args.x1, x2=args.x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 278, in main
    all_files = product_columns(n=8, x1=x1, x2=x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 265, in product_columns
    uuid_code=weather_uuid,
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 173, in computeCrop
    weather = prepareWeather(weather_fname)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 53, in prepareWeather
    weather = CSVWeatherDataProvider(path_to_save_csv_file)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/fileinput/csvweatherdataprovider.py", line 157, in __init__
    self._read_meta(csv_file)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/fileinput/csvweatherdataprovider.py", line 168, in _read_meta
    key, val = stmt.split('=')
ValueError: not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 294, in <module>
    main(x1=args.x1, x2=args.x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 278, in main
    all_files = product_columns(n=8, x1=x1, x2=x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 265, in product_columns
    uuid_code=weather_uuid,
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 173, in computeCrop
    weather = prepareWeather(weather_fname)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 53, in prepareWeather
    weather = CSVWeatherDataProvider(path_to_save_csv_file)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/fileinput/csvweatherdataprovider.py", line 157, in __init__
    self._read_meta(csv_file)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/fileinput/csvweatherdataprovider.py", line 168, in _read_meta
    key, val = stmt.split('=')
ValueError: not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 294, in <module>
    main(x1=args.x1, x2=args.x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 278, in main
    all_files = product_columns(n=8, x1=x1, x2=x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 265, in product_columns
    uuid_code=weather_uuid,
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 173, in computeCrop
    weather = prepareWeather(weather_fname)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 53, in prepareWeather
    weather = CSVWeatherDataProvider(path_to_save_csv_file)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/fileinput/csvweatherdataprovider.py", line 158, in __init__
    self._read_observations(csv_file, delimiter)
Traceback (most recent call last):
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 294, in <module>
    main(x1=args.x1, x2=args.x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 278, in main
    all_files = product_columns(n=8, x1=x1, x2=x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 265, in product_columns
    uuid_code=weather_uuid,
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 173, in computeCrop
    weather = prepareWeather(weather_fname)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 53, in prepareWeather
    weather = CSVWeatherDataProvider(path_to_save_csv_file)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/fileinput/csvweatherdataprovider.py", line 158, in __init__
    self._read_observations(csv_file, delimiter)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/fileinput/csvweatherdataprovider.py", line 195, in _read_observations
    for i, d in enumerate(obs):
  File "/trinity/shared/opt/python-3.6.8/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte
Traceback (most recent call last):
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 294, in <module>
    main(x1=args.x1, x2=args.x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 278, in main
    all_files = product_columns(n=8, x1=x1, x2=x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 265, in product_columns
    uuid_code=weather_uuid,
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 173, in computeCrop
    weather = prepareWeather(weather_fname)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 53, in prepareWeather
    weather = CSVWeatherDataProvider(path_to_save_csv_file)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/fileinput/csvweatherdataprovider.py", line 158, in __init__
    self._read_observations(csv_file, delimiter)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/fileinput/csvweatherdataprovider.py", line 195, in _read_observations
    for i, d in enumerate(obs):
  File "/trinity/shared/opt/python-3.6.8/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte
Traceback (most recent call last):
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 294, in <module>
    main(x1=args.x1, x2=args.x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 278, in main
    all_files = product_columns(n=8, x1=x1, x2=x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 265, in product_columns
    uuid_code=weather_uuid,
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 173, in computeCrop
    weather = prepareWeather(weather_fname)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 53, in prepareWeather
    weather = CSVWeatherDataProvider(path_to_save_csv_file)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/fileinput/csvweatherdataprovider.py", line 158, in __init__
    self._read_observations(csv_file, delimiter)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/fileinput/csvweatherdataprovider.py", line 195, in _read_observations
    for i, d in enumerate(obs):
  File "/trinity/shared/opt/python-3.6.8/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte
Traceback (most recent call last):
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 294, in <module>
    main(x1=args.x1, x2=args.x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 278, in main
    all_files = product_columns(n=8, x1=x1, x2=x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 265, in product_columns
    uuid_code=weather_uuid,
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 173, in computeCrop
    weather = prepareWeather(weather_fname)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 53, in prepareWeather
    weather = CSVWeatherDataProvider(path_to_save_csv_file)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/fileinput/csvweatherdataprovider.py", line 158, in __init__
    self._read_observations(csv_file, delimiter)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/fileinput/csvweatherdataprovider.py", line 195, in _read_observations
    for i, d in enumerate(obs):
  File "/trinity/shared/opt/python-3.6.8/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte
Traceback (most recent call last):
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 294, in <module>
    main(x1=args.x1, x2=args.x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 278, in main
    all_files = product_columns(n=8, x1=x1, x2=x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 265, in product_columns
    uuid_code=weather_uuid,
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 173, in computeCrop
    weather = prepareWeather(weather_fname)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 53, in prepareWeather
    weather = CSVWeatherDataProvider(path_to_save_csv_file)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/fileinput/csvweatherdataprovider.py", line 158, in __init__
    self._read_observations(csv_file, delimiter)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/fileinput/csvweatherdataprovider.py", line 195, in _read_observations
    for i, d in enumerate(obs):
  File "/trinity/shared/opt/python-3.6.8/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte
Traceback (most recent call last):
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 294, in <module>
    main(x1=args.x1, x2=args.x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 278, in main
    all_files = product_columns(n=8, x1=x1, x2=x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 265, in product_columns
    uuid_code=weather_uuid,
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 173, in computeCrop
    weather = prepareWeather(weather_fname)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 53, in prepareWeather
    weather = CSVWeatherDataProvider(path_to_save_csv_file)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/fileinput/csvweatherdataprovider.py", line 158, in __init__
    self._read_observations(csv_file, delimiter)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/fileinput/csvweatherdataprovider.py", line 195, in _read_observations
    for i, d in enumerate(obs):
  File "/trinity/shared/opt/python-3.6.8/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte
Traceback (most recent call last):
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 294, in <module>
    main(x1=args.x1, x2=args.x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 278, in main
    all_files = product_columns(n=8, x1=x1, x2=x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 265, in product_columns
    uuid_code=weather_uuid,
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 173, in computeCrop
    weather = prepareWeather(weather_fname)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 53, in prepareWeather
    weather = CSVWeatherDataProvider(path_to_save_csv_file)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/fileinput/csvweatherdataprovider.py", line 158, in __init__
    self._read_observations(csv_file, delimiter)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/fileinput/csvweatherdataprovider.py", line 195, in _read_observations
    for i, d in enumerate(obs):
  File "/trinity/shared/opt/python-3.6.8/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte
Traceback (most recent call last):
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 294, in <module>
    main(x1=args.x1, x2=args.x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 278, in main
    all_files = product_columns(n=8, x1=x1, x2=x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 265, in product_columns
    uuid_code=weather_uuid,
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 173, in computeCrop
    weather = prepareWeather(weather_fname)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 53, in prepareWeather
    weather = CSVWeatherDataProvider(path_to_save_csv_file)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/fileinput/csvweatherdataprovider.py", line 158, in __init__
    self._read_observations(csv_file, delimiter)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/fileinput/csvweatherdataprovider.py", line 195, in _read_observations
    for i, d in enumerate(obs):
  File "/trinity/shared/opt/python-3.6.8/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte
Traceback (most recent call last):
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 294, in <module>
    main(x1=args.x1, x2=args.x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 278, in main
    all_files = product_columns(n=8, x1=x1, x2=x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 265, in product_columns
    uuid_code=weather_uuid,
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 173, in computeCrop
    weather = prepareWeather(weather_fname)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 53, in prepareWeather
    weather = CSVWeatherDataProvider(path_to_save_csv_file)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/fileinput/csvweatherdataprovider.py", line 158, in __init__
    self._read_observations(csv_file, delimiter)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/fileinput/csvweatherdataprovider.py", line 195, in _read_observations
    for i, d in enumerate(obs):
  File "/trinity/shared/opt/python-3.6.8/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte
Traceback (most recent call last):
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 294, in <module>
    main(x1=args.x1, x2=args.x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 278, in main
    all_files = product_columns(n=8, x1=x1, x2=x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 265, in product_columns
    uuid_code=weather_uuid,
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 173, in computeCrop
    weather = prepareWeather(weather_fname)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 53, in prepareWeather
    weather = CSVWeatherDataProvider(path_to_save_csv_file)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/fileinput/csvweatherdataprovider.py", line 158, in __init__
    self._read_observations(csv_file, delimiter)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/fileinput/csvweatherdataprovider.py", line 195, in _read_observations
    for i, d in enumerate(obs):
  File "/trinity/shared/opt/python-3.6.8/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte
Traceback (most recent call last):
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 294, in <module>
    main(x1=args.x1, x2=args.x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 278, in main
    all_files = product_columns(n=8, x1=x1, x2=x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 265, in product_columns
    uuid_code=weather_uuid,
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 173, in computeCrop
    weather = prepareWeather(weather_fname)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 53, in prepareWeather
    weather = CSVWeatherDataProvider(path_to_save_csv_file)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/fileinput/csvweatherdataprovider.py", line 158, in __init__
    self._read_observations(csv_file, delimiter)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/fileinput/csvweatherdataprovider.py", line 195, in _read_observations
    for i, d in enumerate(obs):
  File "/trinity/shared/opt/python-3.6.8/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte
Traceback (most recent call last):
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 294, in <module>
    main(x1=args.x1, x2=args.x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 278, in main
    all_files = product_columns(n=8, x1=x1, x2=x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 265, in product_columns
    uuid_code=weather_uuid,
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 173, in computeCrop
    weather = prepareWeather(weather_fname)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 53, in prepareWeather
    weather = CSVWeatherDataProvider(path_to_save_csv_file)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/fileinput/csvweatherdataprovider.py", line 158, in __init__
    self._read_observations(csv_file, delimiter)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/fileinput/csvweatherdataprovider.py", line 195, in _read_observations
    for i, d in enumerate(obs):
  File "/trinity/shared/opt/python-3.6.8/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte
Traceback (most recent call last):
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 294, in <module>
    main(x1=args.x1, x2=args.x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 278, in main
    all_files = product_columns(n=8, x1=x1, x2=x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 265, in product_columns
    uuid_code=weather_uuid,
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 173, in computeCrop
    weather = prepareWeather(weather_fname)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 53, in prepareWeather
    weather = CSVWeatherDataProvider(path_to_save_csv_file)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/fileinput/csvweatherdataprovider.py", line 158, in __init__
    self._read_observations(csv_file, delimiter)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/fileinput/csvweatherdataprovider.py", line 195, in _read_observations
    for i, d in enumerate(obs):
  File "/trinity/shared/opt/python-3.6.8/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte
Traceback (most recent call last):
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 294, in <module>
    main(x1=args.x1, x2=args.x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 278, in main
    all_files = product_columns(n=8, x1=x1, x2=x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 265, in product_columns
    uuid_code=weather_uuid,
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 173, in computeCrop
    weather = prepareWeather(weather_fname)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 53, in prepareWeather
    weather = CSVWeatherDataProvider(path_to_save_csv_file)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/fileinput/csvweatherdataprovider.py", line 158, in __init__
    self._read_observations(csv_file, delimiter)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/fileinput/csvweatherdataprovider.py", line 195, in _read_observations
    for i, d in enumerate(obs):
  File "/trinity/shared/opt/python-3.6.8/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte
Traceback (most recent call last):
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 294, in <module>
    main(x1=args.x1, x2=args.x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 278, in main
    all_files = product_columns(n=8, x1=x1, x2=x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 265, in product_columns
    uuid_code=weather_uuid,
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 173, in computeCrop
    weather = prepareWeather(weather_fname)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 53, in prepareWeather
    weather = CSVWeatherDataProvider(path_to_save_csv_file)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/fileinput/csvweatherdataprovider.py", line 158, in __init__
    self._read_observations(csv_file, delimiter)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/fileinput/csvweatherdataprovider.py", line 195, in _read_observations
    for i, d in enumerate(obs):
  File "/trinity/shared/opt/python-3.6.8/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte
Traceback (most recent call last):
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 294, in <module>
    main(x1=args.x1, x2=args.x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 278, in main
    all_files = product_columns(n=8, x1=x1, x2=x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 265, in product_columns
    uuid_code=weather_uuid,
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 173, in computeCrop
    weather = prepareWeather(weather_fname)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 53, in prepareWeather
    weather = CSVWeatherDataProvider(path_to_save_csv_file)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/fileinput/csvweatherdataprovider.py", line 158, in __init__
    self._read_observations(csv_file, delimiter)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/fileinput/csvweatherdataprovider.py", line 195, in _read_observations
    for i, d in enumerate(obs):
  File "/trinity/shared/opt/python-3.6.8/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte
Traceback (most recent call last):
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 294, in <module>
    main(x1=args.x1, x2=args.x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 278, in main
    all_files = product_columns(n=8, x1=x1, x2=x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 265, in product_columns
    uuid_code=weather_uuid,
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 173, in computeCrop
    weather = prepareWeather(weather_fname)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 53, in prepareWeather
    weather = CSVWeatherDataProvider(path_to_save_csv_file)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/fileinput/csvweatherdataprovider.py", line 158, in __init__
    self._read_observations(csv_file, delimiter)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/fileinput/csvweatherdataprovider.py", line 195, in _read_observations
    for i, d in enumerate(obs):
  File "/trinity/shared/opt/python-3.6.8/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/fileinput/csvweatherdataprovider.py", line 195, in _read_observations
    for i, d in enumerate(obs):
  File "/trinity/shared/opt/python-3.6.8/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte
Traceback (most recent call last):
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 294, in <module>
    main(x1=args.x1, x2=args.x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 278, in main
    all_files = product_columns(n=8, x1=x1, x2=x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 265, in product_columns
    uuid_code=weather_uuid,
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 173, in computeCrop
    weather = prepareWeather(weather_fname)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 53, in prepareWeather
    weather = CSVWeatherDataProvider(path_to_save_csv_file)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/fileinput/csvweatherdataprovider.py", line 158, in __init__
    self._read_observations(csv_file, delimiter)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/fileinput/csvweatherdataprovider.py", line 195, in _read_observations
    for i, d in enumerate(obs):
  File "/trinity/shared/opt/python-3.6.8/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte
Traceback (most recent call last):
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 294, in <module>
    main(x1=args.x1, x2=args.x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 278, in main
    all_files = product_columns(n=8, x1=x1, x2=x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 265, in product_columns
    uuid_code=weather_uuid,
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 173, in computeCrop
    weather = prepareWeather(weather_fname)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 53, in prepareWeather
    weather = CSVWeatherDataProvider(path_to_save_csv_file)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/fileinput/csvweatherdataprovider.py", line 158, in __init__
    self._read_observations(csv_file, delimiter)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/fileinput/csvweatherdataprovider.py", line 195, in _read_observations
    for i, d in enumerate(obs):
  File "/trinity/shared/opt/python-3.6.8/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte
Traceback (most recent call last):
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 294, in <module>
    main(x1=args.x1, x2=args.x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 278, in main
    all_files = product_columns(n=8, x1=x1, x2=x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 265, in product_columns
    uuid_code=weather_uuid,
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 173, in computeCrop
    weather = prepareWeather(weather_fname)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 53, in prepareWeather
    weather = CSVWeatherDataProvider(path_to_save_csv_file)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/fileinput/csvweatherdataprovider.py", line 158, in __init__
    self._read_observations(csv_file, delimiter)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/fileinput/csvweatherdataprovider.py", line 195, in _read_observations
    for i, d in enumerate(obs):
  File "/trinity/shared/opt/python-3.6.8/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte
Traceback (most recent call last):
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 294, in <module>
    main(x1=args.x1, x2=args.x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 278, in main
    all_files = product_columns(n=8, x1=x1, x2=x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 265, in product_columns
    uuid_code=weather_uuid,
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 173, in computeCrop
    weather = prepareWeather(weather_fname)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 53, in prepareWeather
    weather = CSVWeatherDataProvider(path_to_save_csv_file)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/fileinput/csvweatherdataprovider.py", line 158, in __init__
    self._read_observations(csv_file, delimiter)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/fileinput/csvweatherdataprovider.py", line 195, in _read_observations
    for i, d in enumerate(obs):
  File "/trinity/shared/opt/python-3.6.8/lib/python3.6/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: line contains NULL byte
srun: error: cn22: task 6: Exited with exit code 1
srun: error: cn27: tasks 7-17: Exited with exit code 1
srun: error: cn22: tasks 0-5: Exited with exit code 1
srun: error: cn33: tasks 18-23: Exited with exit code 1
Traceback (most recent call last):
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 294, in <module>
    main(x1=args.x1, x2=args.x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 278, in main
    all_files = product_columns(n=8, x1=x1, x2=x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 265, in product_columns
    uuid_code=weather_uuid,
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 173, in computeCrop
    weather = prepareWeather(weather_fname)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 53, in prepareWeather
    weather = CSVWeatherDataProvider(path_to_save_csv_file)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/fileinput/csvweatherdataprovider.py", line 158, in __init__
    self._read_observations(csv_file, delimiter)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/fileinput/csvweatherdataprovider.py", line 202, in _read_observations
    value = float(d[label])
TypeError: float() argument must be a string or a number, not 'NoneType'
Traceback (most recent call last):
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 294, in <module>
    main(x1=args.x1, x2=args.x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 278, in main
    all_files = product_columns(n=8, x1=x1, x2=x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 265, in product_columns
    uuid_code=weather_uuid,
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 173, in computeCrop
    weather = prepareWeather(weather_fname)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 31, in prepareWeather
    weather_df = pd.read_csv(in_fname)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 454, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 948, in __init__
    self._make_engine(self.engine)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1180, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 2010, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 540, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
Traceback (most recent call last):
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 294, in <module>
    main(x1=args.x1, x2=args.x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 278, in main
    all_files = product_columns(n=8, x1=x1, x2=x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 265, in product_columns
    uuid_code=weather_uuid,
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 173, in computeCrop
    weather = prepareWeather(weather_fname)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 53, in prepareWeather
    weather = CSVWeatherDataProvider(path_to_save_csv_file)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/fileinput/csvweatherdataprovider.py", line 158, in __init__
    self._read_observations(csv_file, delimiter)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/fileinput/csvweatherdataprovider.py", line 202, in _read_observations
    value = float(d[label])
TypeError: float() argument must be a string or a number, not 'NoneType'
Traceback (most recent call last):
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 294, in <module>
    main(x1=args.x1, x2=args.x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 278, in main
    all_files = product_columns(n=8, x1=x1, x2=x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 265, in product_columns
    uuid_code=weather_uuid,
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 173, in computeCrop
    weather = prepareWeather(weather_fname)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 53, in prepareWeather
    weather = CSVWeatherDataProvider(path_to_save_csv_file)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/fileinput/csvweatherdataprovider.py", line 155, in __init__
    with open(csv_fname, 'r') as csv_file:
FileNotFoundError: [Errno 2] No such file or directory: '/trinity/home/m.gasanov/agriculture/3s-Article/predicted_weather/interval_data/0_2_0_0_0_0_WOFOST.csv'
Traceback (most recent call last):
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 294, in <module>
    main(x1=args.x1, x2=args.x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 278, in main
    all_files = product_columns(n=8, x1=x1, x2=x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 265, in product_columns
    uuid_code=weather_uuid,
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 173, in computeCrop
    weather = prepareWeather(weather_fname)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 53, in prepareWeather
    weather = CSVWeatherDataProvider(path_to_save_csv_file)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/fileinput/csvweatherdataprovider.py", line 158, in __init__
    self._read_observations(csv_file, delimiter)
Traceback (most recent call last):
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 294, in <module>
    main(x1=args.x1, x2=args.x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 278, in main
    all_files = product_columns(n=8, x1=x1, x2=x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 265, in product_columns
    uuid_code=weather_uuid,
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 173, in computeCrop
    weather = prepareWeather(weather_fname)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 53, in prepareWeather
    weather = CSVWeatherDataProvider(path_to_save_csv_file)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/fileinput/csvweatherdataprovider.py", line 152, in __init__
    raise PCSEError(msg)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/fileinput/csvweatherdataprovider.py", line 202, in _read_observations
    value = float(d[label])
TypeError: float() argument must be a string or a number, not 'NoneType'
pcse.exceptions.PCSEError: Cannot find weather file at: /trinity/home/m.gasanov/agriculture/3s-Article/predicted_weather/interval_data/0_2_0_0_0_0_WOFOST.csv
srun: error: cn33: tasks 18-21: Exited with exit code 1
srun: error: cn22: tasks 1,5: Exited with exit code 1
Traceback (most recent call last):
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 294, in <module>
    main(x1=args.x1, x2=args.x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 278, in main
    all_files = product_columns(n=8, x1=x1, x2=x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 265, in product_columns
    uuid_code=weather_uuid,
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 173, in computeCrop
    weather = prepareWeather(weather_fname)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 55, in prepareWeather
    os.remove(path_to_save_csv_file)
FileNotFoundError: [Errno 2] No such file or directory: '/trinity/home/m.gasanov/agriculture/3s-Article/predicted_weather/interval_data/0_2_0_0_0_0_WOFOST.csv'
Traceback (most recent call last):
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 294, in <module>
    main(x1=args.x1, x2=args.x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 278, in main
    all_files = product_columns(n=8, x1=x1, x2=x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 265, in product_columns
    uuid_code=weather_uuid,
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 173, in computeCrop
    weather = prepareWeather(weather_fname)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 55, in prepareWeather
    os.remove(path_to_save_csv_file)
FileNotFoundError: [Errno 2] No such file or directory: '/trinity/home/m.gasanov/agriculture/3s-Article/predicted_weather/interval_data/0_2_0_0_0_0_WOFOST.csv'
Traceback (most recent call last):
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 294, in <module>
    main(x1=args.x1, x2=args.x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 278, in main
    all_files = product_columns(n=8, x1=x1, x2=x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 265, in product_columns
    uuid_code=weather_uuid,
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 173, in computeCrop
    weather = prepareWeather(weather_fname)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 55, in prepareWeather
    os.remove(path_to_save_csv_file)
FileNotFoundError: [Errno 2] No such file or directory: '/trinity/home/m.gasanov/agriculture/3s-Article/predicted_weather/interval_data/0_2_0_0_0_0_WOFOST.csv'
Traceback (most recent call last):
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 294, in <module>
    main(x1=args.x1, x2=args.x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 278, in main
    all_files = product_columns(n=8, x1=x1, x2=x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 265, in product_columns
    uuid_code=weather_uuid,
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 173, in computeCrop
    weather = prepareWeather(weather_fname)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 55, in prepareWeather
    os.remove(path_to_save_csv_file)
FileNotFoundError: [Errno 2] No such file or directory: '/trinity/home/m.gasanov/agriculture/3s-Article/predicted_weather/interval_data/0_2_0_0_0_0_WOFOST.csv'
Traceback (most recent call last):
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 294, in <module>
    main(x1=args.x1, x2=args.x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 278, in main
    all_files = product_columns(n=8, x1=x1, x2=x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 265, in product_columns
    uuid_code=weather_uuid,
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 173, in computeCrop
    weather = prepareWeather(weather_fname)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 55, in prepareWeather
    os.remove(path_to_save_csv_file)
FileNotFoundError: [Errno 2] No such file or directory: '/trinity/home/m.gasanov/agriculture/3s-Article/predicted_weather/interval_data/0_2_0_0_0_0_WOFOST.csv'
Traceback (most recent call last):
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 294, in <module>
    main(x1=args.x1, x2=args.x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 278, in main
    all_files = product_columns(n=8, x1=x1, x2=x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 265, in product_columns
    uuid_code=weather_uuid,
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 173, in computeCrop
    weather = prepareWeather(weather_fname)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 55, in prepareWeather
    os.remove(path_to_save_csv_file)
FileNotFoundError: [Errno 2] No such file or directory: '/trinity/home/m.gasanov/agriculture/3s-Article/predicted_weather/interval_data/0_2_0_0_0_0_WOFOST.csv'
Traceback (most recent call last):
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 294, in <module>
    main(x1=args.x1, x2=args.x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 278, in main
    all_files = product_columns(n=8, x1=x1, x2=x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 265, in product_columns
    uuid_code=weather_uuid,
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 173, in computeCrop
    weather = prepareWeather(weather_fname)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 55, in prepareWeather
    os.remove(path_to_save_csv_file)
FileNotFoundError: [Errno 2] No such file or directory: '/trinity/home/m.gasanov/agriculture/3s-Article/predicted_weather/interval_data/0_2_0_0_0_0_WOFOST.csv'
Traceback (most recent call last):
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 294, in <module>
    main(x1=args.x1, x2=args.x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 278, in main
    all_files = product_columns(n=8, x1=x1, x2=x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 265, in product_columns
    uuid_code=weather_uuid,
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 173, in computeCrop
    weather = prepareWeather(weather_fname)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 55, in prepareWeather
    os.remove(path_to_save_csv_file)
FileNotFoundError: [Errno 2] No such file or directory: '/trinity/home/m.gasanov/agriculture/3s-Article/predicted_weather/interval_data/0_2_0_0_0_0_WOFOST.csv'
Traceback (most recent call last):
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 294, in <module>
    main(x1=args.x1, x2=args.x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 278, in main
    all_files = product_columns(n=8, x1=x1, x2=x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 265, in product_columns
    uuid_code=weather_uuid,
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 173, in computeCrop
    weather = prepareWeather(weather_fname)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 55, in prepareWeather
    os.remove(path_to_save_csv_file)
FileNotFoundError: [Errno 2] No such file or directory: '/trinity/home/m.gasanov/agriculture/3s-Article/predicted_weather/interval_data/0_2_0_0_0_0_WOFOST.csv'
Traceback (most recent call last):
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 294, in <module>
    main(x1=args.x1, x2=args.x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 278, in main
    all_files = product_columns(n=8, x1=x1, x2=x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 265, in product_columns
    uuid_code=weather_uuid,
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 173, in computeCrop
    weather = prepareWeather(weather_fname)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 55, in prepareWeather
    os.remove(path_to_save_csv_file)
FileNotFoundError: [Errno 2] No such file or directory: '/trinity/home/m.gasanov/agriculture/3s-Article/predicted_weather/interval_data/0_2_0_0_0_0_WOFOST.csv'
Traceback (most recent call last):
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 294, in <module>
    main(x1=args.x1, x2=args.x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 278, in main
    all_files = product_columns(n=8, x1=x1, x2=x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 265, in product_columns
    uuid_code=weather_uuid,
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 173, in computeCrop
    weather = prepareWeather(weather_fname)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 55, in prepareWeather
    os.remove(path_to_save_csv_file)
FileNotFoundError: [Errno 2] No such file or directory: '/trinity/home/m.gasanov/agriculture/3s-Article/predicted_weather/interval_data/0_2_0_0_0_0_WOFOST.csv'
Traceback (most recent call last):
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 294, in <module>
    main(x1=args.x1, x2=args.x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 278, in main
    all_files = product_columns(n=8, x1=x1, x2=x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 265, in product_columns
    uuid_code=weather_uuid,
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 173, in computeCrop
    weather = prepareWeather(weather_fname)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 55, in prepareWeather
    os.remove(path_to_save_csv_file)
FileNotFoundError: [Errno 2] No such file or directory: '/trinity/home/m.gasanov/agriculture/3s-Article/predicted_weather/interval_data/0_2_0_0_0_0_WOFOST.csv'
Traceback (most recent call last):
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/base/weather.py", line 367, in __call__
    return self.store[(keydate, 0)]
KeyError: (datetime.date(2015, 4, 25), 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 294, in <module>
    main(x1=args.x1, x2=args.x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 278, in main
    all_files = product_columns(n=8, x1=x1, x2=x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 265, in product_columns
    uuid_code=weather_uuid,
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 194, in computeCrop
    crop_end_type="harvest",
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 147, in run_wofost
    model_runner = modelDict[model_type](params, weather, agro)
Traceback (most recent call last):
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 294, in <module>
    main(x1=args.x1, x2=args.x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 278, in main
    all_files = product_columns(n=8, x1=x1, x2=x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 265, in product_columns
    uuid_code=weather_uuid,
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 173, in computeCrop
    weather = prepareWeather(weather_fname)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 55, in prepareWeather
    os.remove(path_to_save_csv_file)
FileNotFoundError: [Errno 2] No such file or directory: '/trinity/home/m.gasanov/agriculture/3s-Article/predicted_weather/interval_data/0_2_0_0_0_0_WOFOST.csv'
Traceback (most recent call last):
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 294, in <module>
    main(x1=args.x1, x2=args.x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 278, in main
    all_files = product_columns(n=8, x1=x1, x2=x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 265, in product_columns
    uuid_code=weather_uuid,
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 173, in computeCrop
    weather = prepareWeather(weather_fname)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 55, in prepareWeather
    os.remove(path_to_save_csv_file)
FileNotFoundError: [Errno 2] No such file or directory: '/trinity/home/m.gasanov/agriculture/3s-Article/predicted_weather/interval_data/0_2_0_0_0_0_WOFOST.csv'
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/models.py", line 33, in __init__
    config=self.config)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/engine.py", line 147, in __init__
    self.drv = self._get_driving_variables(self.day)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/engine.py", line 337, in _get_driving_variables
    drv = self.weatherdataprovider(day)
  File "/trinity/home/m.gasanov/.local/lib/python3.6/site-packages/pcse/base/weather.py", line 370, in __call__
    raise exc.WeatherDataProviderError(msg)
pcse.exceptions.WeatherDataProviderError: No weather data for 2015-04-25.
Traceback (most recent call last):
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 294, in <module>
    main(x1=args.x1, x2=args.x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 278, in main
    all_files = product_columns(n=8, x1=x1, x2=x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 265, in product_columns
    uuid_code=weather_uuid,
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 173, in computeCrop
    weather = prepareWeather(weather_fname)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 55, in prepareWeather
    os.remove(path_to_save_csv_file)
FileNotFoundError: [Errno 2] No such file or directory: '/trinity/home/m.gasanov/agriculture/3s-Article/predicted_weather/interval_data/0_2_0_0_0_0_WOFOST.csv'
Traceback (most recent call last):
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 294, in <module>
    main(x1=args.x1, x2=args.x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 278, in main
    all_files = product_columns(n=8, x1=x1, x2=x2)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 265, in product_columns
    uuid_code=weather_uuid,
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 173, in computeCrop
    weather = prepareWeather(weather_fname)
  File "/trinity/home/m.gasanov/agriculture/3s-Article/run_wofost.py", line 55, in prepareWeather
    os.remove(path_to_save_csv_file)
FileNotFoundError: [Errno 2] No such file or directory: '/trinity/home/m.gasanov/agriculture/3s-Article/predicted_weather/interval_data/0_2_0_0_0_0_WOFOST.csv'
srun: error: cn22: tasks 0,2-4,6: Exited with exit code 1
srun: error: cn27: tasks 7-9,11-17: Exited with exit code 1
srun: error: cn33: tasks 22-23: Exited with exit code 1
slurmstepd: error: *** JOB 4972182 ON cn22 CANCELLED AT 2022-10-19T14:23:52 ***
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
